name: sprint
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.2
  awesome_dialog: ^3.1.0
  dio: ^5.3.0
  shared_preferences: ^2.2.2
  flutter_otp_text_field: ^1.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
     - family: Blinker
       fonts:
        - asset: assets/fonts/Blinker-Regular.ttf